Replace () with (void) in function prototypes
() and (void) are 2 different things in C, and can cause gcc warnings:

error: function declaration isn't a prototype [-Werror=strict-prototypes]
 idevice_error_t idevice_event_unsubscribe();

This commit replaces () with (void) in installed headers.